### ISSUE TITLE
Could you provide an example?

### ISSUE THREAD

**Issue by diroru** [timdp/metalsmith-discover-helpers#9]
Am really sorry for the beginner level, but could you possibly supply a concise example for how the contents of a self-contained helper might look like?

It would be much appreciated!

Cheers and thanks a lot!

**Comment by timdp** [comment]
It's been ages since I used Metalsmith, but I skimmed through an old repo of ours that uses them. Looks like a helper module is just a JS file that exports a function. Here's one that we wrote to render Markdown:

```js
'use strict'

var marked = require('marked')
var Handlebars = require('handlebars')
var path = require('path')

var PKG = require(path.join(__dirname, '..', 'package.json'))

marked.setOptions(PKG.marked)

module.exports = function (str) {
  if (typeof str !== 'string') {
    return ''
  }

  var options = {}
  var optionNames = Array.prototype.slice.call(arguments, 1, arguments.length - 1)
  optionNames.forEach(function (name) {
    options[name] = true
  })
  return new Handlebars.SafeString(marked(str.toString(), options))
}
```

In the Handlebars template, we just use it as:

```hbs
{{marked templateVariableWithMarkdownText}}
```

**Comment by diroru** [comment]
Many thanks, it works!

– presumably the above file needs to be called `marked.js`.

Cheers!
